# Reference:
#   https://github.com/wikimedia/restbase/blob/master/config.example.yaml

services:
  - name: restbase
    module: hyperswitch
    conf:
      port: 7231
      salt: secret
      default_page_size: 125
      user_agent: RESTBase
      ui_name: RESTBase
      ui_url: https://www.mediawiki.org/wiki/RESTBase
      ui_title: RESTBase docs
      spec:
        x-request-filters:
          - path: lib/security_response_header_filter.js
          - path: lib/normalize_headers_filter.js
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: MEDIAWIKI_APIS_URI
                  forward_headers: true
                - pattern: PARSOID_URI
                  forward_headers: true
                - pattern: /^https?:\/\//
        paths:
          /{domain:MEDIAWIKI_APIS_DOMAIN}:
            x-modules:
              - path: projects/example.yaml
                options:
                  action:
                    apiUriTemplate: MEDIAWIKI_APIS_URI
                    baseUriTemplate: "{{'http://localhost:7231/{domain}/v1'}}"
                  parsoid:
                    host: PARSOID_URI
                  table:
                    backend: sqlite
                    dbname: db.sqlite3
                    pool_idle_timeout: 20000
                    retry_delay: 250
                    retry_limit: 10
                    show_sql: false
                  mobileapps:
                    host: https://appservice.wmflabs.org
                  purged_cache_control: s-maxage=0, max-age=86400
                  purged_cache_control_client_cache: s-maxage=0, max-age=300

info:
  name: restbase

logging:
  name: restbase
  level: info
