#!/usr/bin/env node
'use strict'

const fs = require('fs').promises;

const CONFIG_FILE = '/srv/restbase/config.yaml';

main();

async function main() {
  // Start reading files
  const configPromise = fs.readFile(CONFIG_FILE, 'utf8');

  // Update config.yaml
  let config = await configPromise;
  config = config.replace(/PARSOID_URI/g, process.env.PARSOID_URI || 'http://parsoid:8000');
  config = config.replace(/MEDIAWIKI_APIS_URI/g, process.env.MEDIAWIKI_APIS_URI || 'http://http/api.php');
  config = config.replace(/MEDIAWIKI_APIS_DOMAIN/g, process.env.MEDIAWIKI_APIS_DOMAIN || 'femiwiki.com');

  await fs.writeFile(CONFIG_FILE, config);
}
