#!/usr/bin/env node

const secretFile = '/a/secret.php';
const configFile = '/srv/restbase/config.yaml';

main();

async function main() {
  const fs = require('fs').promises;

  // Read secrets roughly from /a/secret.php
  const secret = await fs.readFile(secretFile, 'utf8');

  const hostname = secret.match(/^\$wgRESTBaseCassandraServer\s*=\s*['"](.+)['"]\s*\;/m)[1];
  const username = secret.match(/^\$wgRESTBaseCassandraUser\s*=\s*['"](.+)['"]\s*\;/m)[1];
  const password = secret.match(/^\$wgRESTBaseCassandraPassword\s*=\s*['"](.+)['"]\s*\;/m)[1];

  // Update config.yaml
  let config = await fs.readFile(configFile, 'utf8');

  config = config.replace(/DB_HOSTNAME/g, hostname);
  config = config.replace(/DB_USERNAME/g, username);
  config = config.replace(/DB_PASSWORD/g, password);
  config = config.replace(/MEDIAWIKI_APIS_URI/g, process.env.MEDIAWIKI_APIS_URI || 'http://http/api.php');
  config = config.replace(/PARSOID_URI/g, process.env.PARSOID_URI || 'http://parsoid:8000');
  config = config.replace(/MEDIAWIKI_APIS_DOMAIN/g, process.env.MEDIAWIKI_APIS_DOMAIN || 'femiwiki.com');

  await fs.writeFile(configFile, config);
}
