#!/usr/bin/env node
'use strict';

const fs = require('fs').promises;

main();

async function replaceInFile(path, replaces) {
  // Start reading files
  let file = await fs.readFile(path, 'utf8');

  // Update file
  if (replaces[0].constructor === Array)
    for (const r of replaces) {
      file = file.replace(r[0], r[1]);
    }
  else {
    file = file.replace(replaces[0], replaces[1]);
  }

  // Write to file
  await fs.writeFile(path, file);
}

async function main() {
  const ROOT = '/srv/restbase';
  const DOMAIN = process.env.MEDIAWIKI_APIS_DOMAIN || 'femiwiki.com';

  await replaceInFile(`${ROOT}/config.yaml`, [
    [
      /MEDIAWIKI_APIS_URI/g,
      process.env.MEDIAWIKI_APIS_URI || 'http://http/api.php',
    ],
    [/MEDIAWIKI_APIS_DOMAIN/g, DOMAIN],
    [/PARSOID_URI/g, process.env.PARSOID_URI || 'http://parsoid:8000'],
    [/MATHOID_URI/g, process.env.MATHOID_URI || 'http://mathoid:10044'],
  ]);

  await replaceInFile(
    `${ROOT}/node_modules/restbase/v1/mathoid.yaml`,
    [/\/wikimedia\.org\/sys/g, `/${DOMAIN}/sys`]
  );

  await replaceInFile(
    `${ROOT}/node_modules/restbase/sys/mathoid.js`,
    [/\/\/wikimedia\.org\/api\/rest_/g, `//${DOMAIN}/`]
  );
}
